name: Basic Project Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Perform tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.pgrx/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
    
      - name: Install pgrx
        run: |
          if [[ ! -d ~/.pgrx ]]; then
             cargo install --locked cargo-pgrx
             cargo pgrx init
          fi

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings   

      - name: Execute tests
        run: cargo pgrx test pg15
